<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class SamplesTestTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table("samples")->insert([

            array("sample_id"=>"Sample-id1",  "sample_id_suffix"=>"1", "batch_id"=>"2",  "i7_index_id"=>"193",  "i5_index_id"=>"1",  "runs_remaining"=>"16",  "instrument_lane"=>"8",  "plate"=>"plate1",  "well"=>"well1",  "description"=>"description1",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id2",  "sample_id_suffix"=>"1", "batch_id"=>"2",  "i7_index_id"=>"194",  "i5_index_id"=>"2",  "runs_remaining"=>"55",  "instrument_lane"=>"8",  "plate"=>"plate2",  "well"=>"well2",  "description"=>"description2",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id3",  "sample_id_suffix"=>"1", "batch_id"=>"2",  "i7_index_id"=>"195",  "i5_index_id"=>"3",  "runs_remaining"=>"8",  "instrument_lane"=>"1",  "plate"=>"plate3",  "well"=>"well3",  "description"=>"description3",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id4",  "sample_id_suffix"=>"1", "batch_id"=>"2",  "i7_index_id"=>"196",  "i5_index_id"=>"4",  "runs_remaining"=>"44",  "instrument_lane"=>"6",  "plate"=>"plate4",  "well"=>"well4",  "description"=>"description4",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id5",  "sample_id_suffix"=>"1", "batch_id"=>"2",  "i7_index_id"=>"196",  "i5_index_id"=>"5",  "runs_remaining"=>"28",  "instrument_lane"=>"3",  "plate"=>"plate5",  "well"=>"well5",  "description"=>"description5",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id6",  "sample_id_suffix"=>"1", "batch_id"=>"2",  "i7_index_id"=>"198",  "i5_index_id"=>"6",  "runs_remaining"=>"1",  "instrument_lane"=>"4",  "plate"=>"plate6",  "well"=>"well6",  "description"=>"description6",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id7",  "sample_id_suffix"=>"1", "batch_id"=>"2",  "i7_index_id"=>"199",  "i5_index_id"=>"7",  "runs_remaining"=>"42",  "instrument_lane"=>"6",  "plate"=>"plate7",  "well"=>"well7",  "description"=>"description7",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id8",  "sample_id_suffix"=>"1", "batch_id"=>"2",  "i7_index_id"=>"200",  "i5_index_id"=>"8",  "runs_remaining"=>"29",  "instrument_lane"=>"2",  "plate"=>"plate8",  "well"=>"well8",  "description"=>"description8",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id9",  "sample_id_suffix"=>"1", "batch_id"=>"2",  "i7_index_id"=>"205",  "i5_index_id"=>"9",  "runs_remaining"=>"18",  "instrument_lane"=>"6",  "plate"=>"plate9",  "well"=>"well9",  "description"=>"description9",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id10",  "sample_id_suffix"=>"1", "batch_id"=>"2",  "i7_index_id"=>"206",  "i5_index_id"=>"10",  "runs_remaining"=>"29",  "instrument_lane"=>"8",  "plate"=>"plate10",  "well"=>"well10",  "description"=>"description10",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id11",  "sample_id_suffix"=>"1", "batch_id"=>"2",  "i7_index_id"=>"207",  "i5_index_id"=>"11",  "runs_remaining"=>"43",  "instrument_lane"=>"1",  "plate"=>"plate11",  "well"=>"well11",  "description"=>"description11",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id12",  "sample_id_suffix"=>"1", "batch_id"=>"2",  "i7_index_id"=>"208",  "i5_index_id"=>"12",  "runs_remaining"=>"30",  "instrument_lane"=>"7",  "plate"=>"plate12",  "well"=>"well12",  "description"=>"description12",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id13",  "sample_id_suffix"=>"1", "batch_id"=>"3",  "i7_index_id"=>"193",  "i5_index_id"=>"1",  "runs_remaining"=>"43",  "instrument_lane"=>"6",  "plate"=>"plate13",  "well"=>"well13",  "description"=>"description13",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id14",  "sample_id_suffix"=>"1", "batch_id"=>"3",  "i7_index_id"=>"194",  "i5_index_id"=>"2",  "runs_remaining"=>"6",  "instrument_lane"=>"2",  "plate"=>"plate14",  "well"=>"well14",  "description"=>"description14",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id15",  "sample_id_suffix"=>"1", "batch_id"=>"3",  "i7_index_id"=>"195",  "i5_index_id"=>"3",  "runs_remaining"=>"12",  "instrument_lane"=>"8",  "plate"=>"plate15",  "well"=>"well15",  "description"=>"description15",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id16",  "sample_id_suffix"=>"1", "batch_id"=>"3",  "i7_index_id"=>"196",  "i5_index_id"=>"4",  "runs_remaining"=>"37",  "instrument_lane"=>"8",  "plate"=>"plate16",  "well"=>"well16",  "description"=>"description16",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id17",  "sample_id_suffix"=>"1", "batch_id"=>"3",  "i7_index_id"=>"197",  "i5_index_id"=>"5",  "runs_remaining"=>"9",  "instrument_lane"=>"7",  "plate"=>"plate17",  "well"=>"well17",  "description"=>"description17",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id18",  "sample_id_suffix"=>"1", "batch_id"=>"3",  "i7_index_id"=>"198",  "i5_index_id"=>"6",  "runs_remaining"=>"9",  "instrument_lane"=>"8",  "plate"=>"plate18",  "well"=>"well18",  "description"=>"description18",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id19",  "sample_id_suffix"=>"1", "batch_id"=>"3",  "i7_index_id"=>"199",  "i5_index_id"=>"7",  "runs_remaining"=>"14",  "instrument_lane"=>"2",  "plate"=>"plate19",  "well"=>"well19",  "description"=>"description19",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id20",  "sample_id_suffix"=>"1", "batch_id"=>"3",  "i7_index_id"=>"200",  "i5_index_id"=>"8",  "runs_remaining"=>"59",  "instrument_lane"=>"1",  "plate"=>"plate20",  "well"=>"well20",  "description"=>"description20",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id21",  "sample_id_suffix"=>"1", "batch_id"=>"3",  "i7_index_id"=>"201",  "i5_index_id"=>"1",  "runs_remaining"=>"19",  "instrument_lane"=>"8",  "plate"=>"plate21",  "well"=>"well21",  "description"=>"description21",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id22",  "sample_id_suffix"=>"1", "batch_id"=>"3",  "i7_index_id"=>"202",  "i5_index_id"=>"2",  "runs_remaining"=>"51",  "instrument_lane"=>"5",  "plate"=>"plate22",  "well"=>"well22",  "description"=>"description22",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id23",  "sample_id_suffix"=>"1", "batch_id"=>"3",  "i7_index_id"=>"203",  "i5_index_id"=>"3",  "runs_remaining"=>"1",  "instrument_lane"=>"5",  "plate"=>"plate23",  "well"=>"well23",  "description"=>"description23",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id24",  "sample_id_suffix"=>"1", "batch_id"=>"3",  "i7_index_id"=>"204",  "i5_index_id"=>"4",  "runs_remaining"=>"20",  "instrument_lane"=>"8",  "plate"=>"plate24",  "well"=>"well24",  "description"=>"description24",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id25",  "sample_id_suffix"=>"1", "batch_id"=>"3",  "i7_index_id"=>"204",  "i5_index_id"=>"5",  "runs_remaining"=>"50",  "instrument_lane"=>"6",  "plate"=>"plate25",  "well"=>"well25",  "description"=>"description25",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id26",  "sample_id_suffix"=>"1", "batch_id"=>"4",  "i7_index_id"=>"226",  "i5_index_id"=>"26",  "runs_remaining"=>"6",  "instrument_lane"=>"7",  "plate"=>"plate26",  "well"=>"well26",  "description"=>"description26",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id27",  "sample_id_suffix"=>"1", "batch_id"=>"4",  "i7_index_id"=>"227",  "i5_index_id"=>"27",  "runs_remaining"=>"17",  "instrument_lane"=>"3",  "plate"=>"plate27",  "well"=>"well27",  "description"=>"description27",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id28",  "sample_id_suffix"=>"1", "batch_id"=>"4",  "i7_index_id"=>"228",  "i5_index_id"=>"28",  "runs_remaining"=>"60",  "instrument_lane"=>"3",  "plate"=>"plate28",  "well"=>"well28",  "description"=>"description28",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id29",  "sample_id_suffix"=>"1", "batch_id"=>"4",  "i7_index_id"=>"229",  "i5_index_id"=>"29",  "runs_remaining"=>"43",  "instrument_lane"=>"1",  "plate"=>"plate29",  "well"=>"well29",  "description"=>"description29",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id30",  "sample_id_suffix"=>"1", "batch_id"=>"4",  "i7_index_id"=>"230",  "i5_index_id"=>"30",  "runs_remaining"=>"42",  "instrument_lane"=>"5",  "plate"=>"plate30",  "well"=>"well30",  "description"=>"description30",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id31",  "sample_id_suffix"=>"1", "batch_id"=>"4",  "i7_index_id"=>"231",  "i5_index_id"=>"31",  "runs_remaining"=>"9",  "instrument_lane"=>"2",  "plate"=>"plate31",  "well"=>"well31",  "description"=>"description31",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id32",  "sample_id_suffix"=>"1", "batch_id"=>"4",  "i7_index_id"=>"232",  "i5_index_id"=>"32",  "runs_remaining"=>"14",  "instrument_lane"=>"8",  "plate"=>"plate32",  "well"=>"well32",  "description"=>"description32",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id33",  "sample_id_suffix"=>"1", "batch_id"=>"4",  "i7_index_id"=>"321",  "i5_index_id"=>"33",  "runs_remaining"=>"50",  "instrument_lane"=>"5",  "plate"=>"plate33",  "well"=>"well33",  "description"=>"description33",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id34",  "sample_id_suffix"=>"1", "batch_id"=>"4",  "i7_index_id"=>"322",  "i5_index_id"=>"34",  "runs_remaining"=>"50",  "instrument_lane"=>"8",  "plate"=>"plate34",  "well"=>"well34",  "description"=>"description34",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id35",  "sample_id_suffix"=>"1", "batch_id"=>"4",  "i7_index_id"=>"322",  "i5_index_id"=>"35",  "runs_remaining"=>"58",  "instrument_lane"=>"2",  "plate"=>"plate35",  "well"=>"well35",  "description"=>"description35",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id36",  "sample_id_suffix"=>"1", "batch_id"=>"4",  "i7_index_id"=>"322",  "i5_index_id"=>"36",  "runs_remaining"=>"45",  "instrument_lane"=>"7",  "plate"=>"plate36",  "well"=>"well36",  "description"=>"description36",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id37",  "sample_id_suffix"=>"1", "batch_id"=>"4",  "i7_index_id"=>"325",  "i5_index_id"=>"37",  "runs_remaining"=>"46",  "instrument_lane"=>"4",  "plate"=>"plate37",  "well"=>"well37",  "description"=>"description37",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id38",  "sample_id_suffix"=>"1", "batch_id"=>"4",  "i7_index_id"=>"326",  "i5_index_id"=>"38",  "runs_remaining"=>"2",  "instrument_lane"=>"2",  "plate"=>"plate38",  "well"=>"well38",  "description"=>"description38",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id39",  "sample_id_suffix"=>"1", "batch_id"=>"4",  "i7_index_id"=>"327",  "i5_index_id"=>"39",  "runs_remaining"=>"25",  "instrument_lane"=>"8",  "plate"=>"plate39",  "well"=>"well39",  "description"=>"description39",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id40",  "sample_id_suffix"=>"1", "batch_id"=>"4",  "i7_index_id"=>"328",  "i5_index_id"=>"40",  "runs_remaining"=>"16",  "instrument_lane"=>"1",  "plate"=>"plate40",  "well"=>"well40",  "description"=>"description40",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id41",  "sample_id_suffix"=>"1", "batch_id"=>"5",  "i7_index_id"=>"329",  "i5_index_id"=>NULL,  "runs_remaining"=>"32",  "instrument_lane"=>"6",  "plate"=>"plate41",  "well"=>"well41",  "description"=>"description41",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id42",  "sample_id_suffix"=>"1", "batch_id"=>"5",  "i7_index_id"=>"330",  "i5_index_id"=>NULL,  "runs_remaining"=>"20",  "instrument_lane"=>"4",  "plate"=>"plate42",  "well"=>"well42",  "description"=>"description42",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id43",  "sample_id_suffix"=>"1", "batch_id"=>"5",  "i7_index_id"=>"331",  "i5_index_id"=>NULL,  "runs_remaining"=>"15",  "instrument_lane"=>"8",  "plate"=>"plate43",  "well"=>"well43",  "description"=>"description43",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id44",  "sample_id_suffix"=>"1", "batch_id"=>"5",  "i7_index_id"=>"332",  "i5_index_id"=>NULL,  "runs_remaining"=>"27",  "instrument_lane"=>"8",  "plate"=>"plate44",  "well"=>"well44",  "description"=>"description44",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id45",  "sample_id_suffix"=>"1", "batch_id"=>"5",  "i7_index_id"=>"333",  "i5_index_id"=>NULL,  "runs_remaining"=>"32",  "instrument_lane"=>"8",  "plate"=>"plate45",  "well"=>"well45",  "description"=>"description45",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id46",  "sample_id_suffix"=>"1", "batch_id"=>"5",  "i7_index_id"=>"334",  "i5_index_id"=>NULL,  "runs_remaining"=>"18",  "instrument_lane"=>"8",  "plate"=>"plate46",  "well"=>"well46",  "description"=>"description46",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id47",  "sample_id_suffix"=>"1", "batch_id"=>"5",  "i7_index_id"=>"335",  "i5_index_id"=>NULL,  "runs_remaining"=>"40",  "instrument_lane"=>"6",  "plate"=>"plate47",  "well"=>"well47",  "description"=>"description47",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id48",  "sample_id_suffix"=>"1", "batch_id"=>"5",  "i7_index_id"=>"336",  "i5_index_id"=>NULL,  "runs_remaining"=>"11",  "instrument_lane"=>"7",  "plate"=>"plate48",  "well"=>"well48",  "description"=>"description48",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id49",  "sample_id_suffix"=>"1", "batch_id"=>"5",  "i7_index_id"=>"337",  "i5_index_id"=>NULL,  "runs_remaining"=>"30",  "instrument_lane"=>"8",  "plate"=>"plate49",  "well"=>"well49",  "description"=>"description49",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample-id50",  "sample_id_suffix"=>"1", "batch_id"=>"5",  "i7_index_id"=>"338",  "i5_index_id"=>NULL,  "runs_remaining"=>"27",  "instrument_lane"=>"8",  "plate"=>"plate50",  "well"=>"well50",  "description"=>"description50",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),


        ]);
    }
}
