<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class SamplesTestTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table("samples")->insert([

            array("sample_id"=>"Sample_id1",  "batch_id"=>"2",  "i7_index_id"=>"193",  "i5_index_id"=>"1",  "runs_remaining"=>"1",  "instrument_lane"=>"1",  "plate"=>"plate1",  "well"=>"well1",  "description"=>"description1",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id2",  "batch_id"=>"2",  "i7_index_id"=>"194",  "i5_index_id"=>"2",  "runs_remaining"=>"2",  "instrument_lane"=>"2",  "plate"=>"plate2",  "well"=>"well2",  "description"=>"description2",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id3",  "batch_id"=>"2",  "i7_index_id"=>"195",  "i5_index_id"=>"3",  "runs_remaining"=>"3",  "instrument_lane"=>"3",  "plate"=>"plate3",  "well"=>"well3",  "description"=>"description3",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id4",  "batch_id"=>"2",  "i7_index_id"=>"196",  "i5_index_id"=>"4",  "runs_remaining"=>"4",  "instrument_lane"=>"4",  "plate"=>"plate4",  "well"=>"well4",  "description"=>"description4",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id5",  "batch_id"=>"2",  "i7_index_id"=>"196",  "i5_index_id"=>"5",  "runs_remaining"=>"5",  "instrument_lane"=>"5",  "plate"=>"plate5",  "well"=>"well5",  "description"=>"description5",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id6",  "batch_id"=>"2",  "i7_index_id"=>"198",  "i5_index_id"=>"6",  "runs_remaining"=>"6",  "instrument_lane"=>"6",  "plate"=>"plate6",  "well"=>"well6",  "description"=>"description6",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id7",  "batch_id"=>"2",  "i7_index_id"=>"199",  "i5_index_id"=>"7",  "runs_remaining"=>"7",  "instrument_lane"=>"7",  "plate"=>"plate7",  "well"=>"well7",  "description"=>"description7",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id8",  "batch_id"=>"2",  "i7_index_id"=>"200",  "i5_index_id"=>"8",  "runs_remaining"=>"8",  "instrument_lane"=>"8",  "plate"=>"plate8",  "well"=>"well8",  "description"=>"description8",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id9",  "batch_id"=>"2",  "i7_index_id"=>"205",  "i5_index_id"=>"9",  "runs_remaining"=>"9",  "instrument_lane"=>"1",  "plate"=>"plate9",  "well"=>"well9",  "description"=>"description9",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id10",  "batch_id"=>"2",  "i7_index_id"=>"206",  "i5_index_id"=>"10",  "runs_remaining"=>"10",  "instrument_lane"=>"2",  "plate"=>"plate10",  "well"=>"well10",  "description"=>"description10",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id11",  "batch_id"=>"2",  "i7_index_id"=>"207",  "i5_index_id"=>"11",  "runs_remaining"=>"11",  "instrument_lane"=>"3",  "plate"=>"plate11",  "well"=>"well11",  "description"=>"description11",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id12",  "batch_id"=>"2",  "i7_index_id"=>"208",  "i5_index_id"=>"12",  "runs_remaining"=>"12",  "instrument_lane"=>"4",  "plate"=>"plate12",  "well"=>"well12",  "description"=>"description12",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id13",  "batch_id"=>"3",  "i7_index_id"=>"209",  "i5_index_id"=>"13",  "runs_remaining"=>"13",  "instrument_lane"=>"5",  "plate"=>"plate13",  "well"=>"well13",  "description"=>"description13",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id14",  "batch_id"=>"3",  "i7_index_id"=>"210",  "i5_index_id"=>"14",  "runs_remaining"=>"14",  "instrument_lane"=>"6",  "plate"=>"plate14",  "well"=>"well14",  "description"=>"description14",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id15",  "batch_id"=>"3",  "i7_index_id"=>"211",  "i5_index_id"=>"15",  "runs_remaining"=>"15",  "instrument_lane"=>"7",  "plate"=>"plate15",  "well"=>"well15",  "description"=>"description15",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id16",  "batch_id"=>"3",  "i7_index_id"=>"212",  "i5_index_id"=>"16",  "runs_remaining"=>"16",  "instrument_lane"=>"8",  "plate"=>"plate16",  "well"=>"well16",  "description"=>"description16",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id17",  "batch_id"=>"3",  "i7_index_id"=>"213",  "i5_index_id"=>"17",  "runs_remaining"=>"17",  "instrument_lane"=>"1",  "plate"=>"plate17",  "well"=>"well17",  "description"=>"description17",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id18",  "batch_id"=>"3",  "i7_index_id"=>"213",  "i5_index_id"=>"18",  "runs_remaining"=>"18",  "instrument_lane"=>"2",  "plate"=>"plate18",  "well"=>"well18",  "description"=>"description18",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id19",  "batch_id"=>"3",  "i7_index_id"=>"213",  "i5_index_id"=>"19",  "runs_remaining"=>"19",  "instrument_lane"=>"3",  "plate"=>"plate19",  "well"=>"well19",  "description"=>"description19",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id20",  "batch_id"=>"3",  "i7_index_id"=>"216",  "i5_index_id"=>"20",  "runs_remaining"=>"20",  "instrument_lane"=>"4",  "plate"=>"plate20",  "well"=>"well20",  "description"=>"description20",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id21",  "batch_id"=>"3",  "i7_index_id"=>"217",  "i5_index_id"=>"21",  "runs_remaining"=>"21",  "instrument_lane"=>"5",  "plate"=>"plate21",  "well"=>"well21",  "description"=>"description21",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id22",  "batch_id"=>"3",  "i7_index_id"=>"218",  "i5_index_id"=>"22",  "runs_remaining"=>"22",  "instrument_lane"=>"6",  "plate"=>"plate22",  "well"=>"well22",  "description"=>"description22",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id23",  "batch_id"=>"3",  "i7_index_id"=>"219",  "i5_index_id"=>"23",  "runs_remaining"=>"23",  "instrument_lane"=>"7",  "plate"=>"plate23",  "well"=>"well23",  "description"=>"description23",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id24",  "batch_id"=>"3",  "i7_index_id"=>"220",  "i5_index_id"=>"24",  "runs_remaining"=>"24",  "instrument_lane"=>"8",  "plate"=>"plate24",  "well"=>"well24",  "description"=>"description24",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id25",  "batch_id"=>"3",  "i7_index_id"=>"225",  "i5_index_id"=>"25",  "runs_remaining"=>"25",  "instrument_lane"=>"1",  "plate"=>"plate25",  "well"=>"well25",  "description"=>"description25",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id26",  "batch_id"=>"4",  "i7_index_id"=>"226",  "i5_index_id"=>"26",  "runs_remaining"=>"26",  "instrument_lane"=>"2",  "plate"=>"plate26",  "well"=>"well26",  "description"=>"description26",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id27",  "batch_id"=>"4",  "i7_index_id"=>"227",  "i5_index_id"=>"27",  "runs_remaining"=>"27",  "instrument_lane"=>"3",  "plate"=>"plate27",  "well"=>"well27",  "description"=>"description27",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id28",  "batch_id"=>"4",  "i7_index_id"=>"228",  "i5_index_id"=>"28",  "runs_remaining"=>"28",  "instrument_lane"=>"4",  "plate"=>"plate28",  "well"=>"well28",  "description"=>"description28",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id29",  "batch_id"=>"4",  "i7_index_id"=>"229",  "i5_index_id"=>"29",  "runs_remaining"=>"29",  "instrument_lane"=>"5",  "plate"=>"plate29",  "well"=>"well29",  "description"=>"description29",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id30",  "batch_id"=>"4",  "i7_index_id"=>"230",  "i5_index_id"=>"30",  "runs_remaining"=>"30",  "instrument_lane"=>"6",  "plate"=>"plate30",  "well"=>"well30",  "description"=>"description30",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id31",  "batch_id"=>"4",  "i7_index_id"=>"231",  "i5_index_id"=>"31",  "runs_remaining"=>"31",  "instrument_lane"=>"7",  "plate"=>"plate31",  "well"=>"well31",  "description"=>"description31",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id32",  "batch_id"=>"4",  "i7_index_id"=>"232",  "i5_index_id"=>"32",  "runs_remaining"=>"32",  "instrument_lane"=>"8",  "plate"=>"plate32",  "well"=>"well32",  "description"=>"description32",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id33",  "batch_id"=>"4",  "i7_index_id"=>"321",  "i5_index_id"=>"33",  "runs_remaining"=>"33",  "instrument_lane"=>"1",  "plate"=>"plate33",  "well"=>"well33",  "description"=>"description33",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id34",  "batch_id"=>"4",  "i7_index_id"=>"322",  "i5_index_id"=>"34",  "runs_remaining"=>"34",  "instrument_lane"=>"2",  "plate"=>"plate34",  "well"=>"well34",  "description"=>"description34",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id35",  "batch_id"=>"4",  "i7_index_id"=>"322",  "i5_index_id"=>"35",  "runs_remaining"=>"35",  "instrument_lane"=>"3",  "plate"=>"plate35",  "well"=>"well35",  "description"=>"description35",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id36",  "batch_id"=>"4",  "i7_index_id"=>"322",  "i5_index_id"=>"36",  "runs_remaining"=>"36",  "instrument_lane"=>"4",  "plate"=>"plate36",  "well"=>"well36",  "description"=>"description36",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id37",  "batch_id"=>"4",  "i7_index_id"=>"325",  "i5_index_id"=>"37",  "runs_remaining"=>"37",  "instrument_lane"=>"5",  "plate"=>"plate37",  "well"=>"well37",  "description"=>"description37",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id38",  "batch_id"=>"4",  "i7_index_id"=>"326",  "i5_index_id"=>"38",  "runs_remaining"=>"38",  "instrument_lane"=>"6",  "plate"=>"plate38",  "well"=>"well38",  "description"=>"description38",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id39",  "batch_id"=>"4",  "i7_index_id"=>"327",  "i5_index_id"=>"39",  "runs_remaining"=>"39",  "instrument_lane"=>"7",  "plate"=>"plate39",  "well"=>"well39",  "description"=>"description39",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id40",  "batch_id"=>"4",  "i7_index_id"=>"328",  "i5_index_id"=>"40",  "runs_remaining"=>"40",  "instrument_lane"=>"8",  "plate"=>"plate40",  "well"=>"well40",  "description"=>"description40",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id41",  "batch_id"=>"5",  "i7_index_id"=>"329",  "i5_index_id"=>"3",  "runs_remaining"=>"41",  "instrument_lane"=>"1",  "plate"=>"plate41",  "well"=>"well41",  "description"=>"description41",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id42",  "batch_id"=>"5",  "i7_index_id"=>"330",  "i5_index_id"=>"3",  "runs_remaining"=>"42",  "instrument_lane"=>"2",  "plate"=>"plate42",  "well"=>"well42",  "description"=>"description42",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id43",  "batch_id"=>"5",  "i7_index_id"=>"331",  "i5_index_id"=>"3",  "runs_remaining"=>"43",  "instrument_lane"=>"3",  "plate"=>"plate43",  "well"=>"well43",  "description"=>"description43",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id44",  "batch_id"=>"5",  "i7_index_id"=>"332",  "i5_index_id"=>"3",  "runs_remaining"=>"44",  "instrument_lane"=>"4",  "plate"=>"plate44",  "well"=>"well44",  "description"=>"description44",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id45",  "batch_id"=>"5",  "i7_index_id"=>"333",  "i5_index_id"=>"3",  "runs_remaining"=>"45",  "instrument_lane"=>"5",  "plate"=>"plate45",  "well"=>"well45",  "description"=>"description45",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id46",  "batch_id"=>"5",  "i7_index_id"=>"334",  "i5_index_id"=>"3",  "runs_remaining"=>"46",  "instrument_lane"=>"6",  "plate"=>"plate46",  "well"=>"well46",  "description"=>"description46",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id47",  "batch_id"=>"5",  "i7_index_id"=>"335",  "i5_index_id"=>"3",  "runs_remaining"=>"47",  "instrument_lane"=>"7",  "plate"=>"plate47",  "well"=>"well47",  "description"=>"description47",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id48",  "batch_id"=>"5",  "i7_index_id"=>"336",  "i5_index_id"=>"3",  "runs_remaining"=>"48",  "instrument_lane"=>"8",  "plate"=>"plate48",  "well"=>"well48",  "description"=>"description48",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id49",  "batch_id"=>"5",  "i7_index_id"=>"337",  "i5_index_id"=>"3",  "runs_remaining"=>"49",  "instrument_lane"=>"1",  "plate"=>"plate49",  "well"=>"well49",  "description"=>"description49",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),
            array("sample_id"=>"Sample_id50",  "batch_id"=>"5",  "i7_index_id"=>"338",  "i5_index_id"=>"3",  "runs_remaining"=>"50",  "instrument_lane"=>"2",  "plate"=>"plate50",  "well"=>"well50",  "description"=>"description50",  "created_at"=>  Carbon::now(),  "updated_at"=>Carbon::now()),


        ]);
    }
}
