<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class UpdateI7TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('i7_index')->insert(
            array(
                array("index_set_id"=>"12", "index"=>"TS-INV-HE-01", "sequence"=>"ATCACG", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"12", "index"=>"TS-INV-HE-02", "sequence"=>"CGATGT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"12", "index"=>"TS-INV-HE-03", "sequence"=>"TTAGGC", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"12", "index"=>"TS-INV-HE-04", "sequence"=>"TGACCA", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"12", "index"=>"TS-INV-HE-05", "sequence"=>"ACAGTG", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"12", "index"=>"TS-INV-HE-06", "sequence"=>"GCCAAT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"12", "index"=>"TS-INV-HE-07", "sequence"=>"CAGATC", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"12", "index"=>"TS-INV-HE-08", "sequence"=>"ACTTGA", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"12", "index"=>"TS-INV-HE-09", "sequence"=>"GATCAG", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"12", "index"=>"TS-INV-HE-10", "sequence"=>"TAGCTT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"12", "index"=>"TS-INV-HE-11", "sequence"=>"GGCTAC", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"12", "index"=>"TS-INV-HE-12", "sequence"=>"CTTGTA", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"12", "index"=>"TS-INV-HE-13", "sequence"=>"AGTCAA", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"12", "index"=>"TS-INV-HE-14", "sequence"=>"AGTTCC", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"12", "index"=>"TS-INV-HE-15", "sequence"=>"ATGTCA", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"12", "index"=>"TS-INV-HE-16", "sequence"=>"CCGTCC", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"12", "index"=>"TS-INV-HE-18", "sequence"=>"GTCCGC", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"12", "index"=>"TS-INV-HE-19", "sequence"=>"GTGAAA", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"12", "index"=>"TS-INV-HE-20", "sequence"=>"GTGGCC", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"12", "index"=>"TS-INV-HE-21", "sequence"=>"GTTTCG", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"12", "index"=>"TS-INV-HE-22", "sequence"=>"CGTACG", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"12", "index"=>"TS-INV-HE-23", "sequence"=>"GAGTGG", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"12", "index"=>"TS-INV-HE-25", "sequence"=>"ACTGAT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"12", "index"=>"TS-INV-HE-27", "sequence"=>"ATTCCT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),

                array("index_set_id"=>"13", "index"=>"TS-INV-HE-01", "sequence"=>"ATCACG", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"13", "index"=>"TS-INV-HE-02", "sequence"=>"CGATGT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"13", "index"=>"TS-INV-HE-03", "sequence"=>"TTAGGC", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"13", "index"=>"TS-INV-HE-04", "sequence"=>"TGACCA", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"13", "index"=>"TS-INV-HE-05", "sequence"=>"ACAGTG", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"13", "index"=>"TS-INV-HE-06", "sequence"=>"GCCAAT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"13", "index"=>"TS-INV-HE-07", "sequence"=>"CAGATC", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"13", "index"=>"TS-INV-HE-08", "sequence"=>"ACTTGA", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"13", "index"=>"TS-INV-HE-09", "sequence"=>"GATCAG", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"13", "index"=>"TS-INV-HE-10", "sequence"=>"TAGCTT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"13", "index"=>"TS-INV-HE-11", "sequence"=>"GGCTAC", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"13", "index"=>"TS-INV-HE-12", "sequence"=>"CTTGTA", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"13", "index"=>"TS-INV-HE-13", "sequence"=>"AGTCAA", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"13", "index"=>"TS-INV-HE-14", "sequence"=>"AGTTCC", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"13", "index"=>"TS-INV-HE-15", "sequence"=>"ATGTCA", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"13", "index"=>"TS-INV-HE-16", "sequence"=>"CCGTCC", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"13", "index"=>"TS-INV-HE-18", "sequence"=>"GTCCGC", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"13", "index"=>"TS-INV-HE-19", "sequence"=>"GTGAAA", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"13", "index"=>"TS-INV-HE-20", "sequence"=>"GTGGCC", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"13", "index"=>"TS-INV-HE-21", "sequence"=>"GTTTCG", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"13", "index"=>"TS-INV-HE-22", "sequence"=>"CGTACG", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"13", "index"=>"TS-INV-HE-23", "sequence"=>"GAGTGG", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"13", "index"=>"TS-INV-HE-25", "sequence"=>"ACTGAT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"13", "index"=>"TS-INV-HE-27", "sequence"=>"ATTCCT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),

                array("index_set_id"=>"14", "index"=>"TS-INV-HE-01", "sequence"=>"ATCACGAT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"14", "index"=>"TS-INV-HE-02", "sequence"=>"CGATGTAT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"14", "index"=>"TS-INV-HE-03", "sequence"=>"TTAGGCAT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"14", "index"=>"TS-INV-HE-04", "sequence"=>"TGACCAAT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"14", "index"=>"TS-INV-HE-05", "sequence"=>"ACAGTGAT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"14", "index"=>"TS-INV-HE-06", "sequence"=>"GCCAATAT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"14", "index"=>"TS-INV-HE-07", "sequence"=>"CAGATCAT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"14", "index"=>"TS-INV-HE-08", "sequence"=>"ACTTGAAT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"14", "index"=>"TS-INV-HE-09", "sequence"=>"GATCAGAT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"14", "index"=>"TS-INV-HE-10", "sequence"=>"TAGCTTAT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"14", "index"=>"TS-INV-HE-11", "sequence"=>"GGCTACAT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"14", "index"=>"TS-INV-HE-12", "sequence"=>"CTTGTAAT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"14", "index"=>"TS-INV-HE-13", "sequence"=>"AGTCAACA", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"14", "index"=>"TS-INV-HE-14", "sequence"=>"AGTTCCGT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"14", "index"=>"TS-INV-HE-15", "sequence"=>"ATGTCAGA", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"14", "index"=>"TS-INV-HE-16", "sequence"=>"CCGTCCCG", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"14", "index"=>"TS-INV-HE-18", "sequence"=>"GTCCGCAC", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"14", "index"=>"TS-INV-HE-19", "sequence"=>"GTGAAACG", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"14", "index"=>"TS-INV-HE-20", "sequence"=>"GTGGCCTT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"14", "index"=>"TS-INV-HE-21", "sequence"=>"GTTTCGGA", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"14", "index"=>"TS-INV-HE-22", "sequence"=>"CGTACGTA", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"14", "index"=>"TS-INV-HE-23", "sequence"=>"GAGTGGAT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"14", "index"=>"TS-INV-HE-25", "sequence"=>"ACTGATAT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"14", "index"=>"TS-INV-HE-27", "sequence"=>"ATTCCTTT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),

                array("index_set_id"=>"15", "index"=>"TS-INV-HE-01", "sequence"=>"ATCACGAT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"15", "index"=>"TS-INV-HE-02", "sequence"=>"CGATGTAT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"15", "index"=>"TS-INV-HE-03", "sequence"=>"TTAGGCAT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"15", "index"=>"TS-INV-HE-04", "sequence"=>"TGACCAAT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"15", "index"=>"TS-INV-HE-05", "sequence"=>"ACAGTGAT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"15", "index"=>"TS-INV-HE-06", "sequence"=>"GCCAATAT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"15", "index"=>"TS-INV-HE-07", "sequence"=>"CAGATCAT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"15", "index"=>"TS-INV-HE-08", "sequence"=>"ACTTGAAT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"15", "index"=>"TS-INV-HE-09", "sequence"=>"GATCAGAT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"15", "index"=>"TS-INV-HE-10", "sequence"=>"TAGCTTAT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"15", "index"=>"TS-INV-HE-11", "sequence"=>"GGCTACAT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"15", "index"=>"TS-INV-HE-12", "sequence"=>"CTTGTAAT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"15", "index"=>"TS-INV-HE-13", "sequence"=>"AGTCAACA", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"15", "index"=>"TS-INV-HE-14", "sequence"=>"AGTTCCGT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"15", "index"=>"TS-INV-HE-15", "sequence"=>"ATGTCAGA", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"15", "index"=>"TS-INV-HE-16", "sequence"=>"CCGTCCCG", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"15", "index"=>"TS-INV-HE-18", "sequence"=>"GTCCGCAC", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"15", "index"=>"TS-INV-HE-19", "sequence"=>"GTGAAACG", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"15", "index"=>"TS-INV-HE-20", "sequence"=>"GTGGCCTT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"15", "index"=>"TS-INV-HE-21", "sequence"=>"GTTTCGGA", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"15", "index"=>"TS-INV-HE-22", "sequence"=>"CGTACGTA", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"15", "index"=>"TS-INV-HE-23", "sequence"=>"GAGTGGAT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"15", "index"=>"TS-INV-HE-25", "sequence"=>"ACTGATAT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
                array("index_set_id"=>"15", "index"=>"TS-INV-HE-27", "sequence"=>"ATTCCTTT", "created_at"=>Carbon::now(), "updated_at"=>Carbon::now()),
            ));
    }
}
