<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateIndexi7Table extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('i7_index', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('i7_index_set_id')->unsigned();
            $table->string('index', 16);
            $table->string('sequence', 16);

            $table->foreign('i7_index_set_id')->references('id')->on('i7_index_set');


            $table->timestamps();
        });
        DB::table('i7_index')->insert(
            array(

                array("i7_index_set_id"=>"1",  "index"=>"A01",  "sequence"=>"ATGCCTAA"),
                array("i7_index_set_id"=>"1",  "index"=>"B01",  "sequence"=>"GAATCTGA"),
                array("i7_index_set_id"=>"1",  "index"=>"C01",  "sequence"=>"AACGTGAT"),
                array("i7_index_set_id"=>"1",  "index"=>"D01",  "sequence"=>"CACTTCGA"),
                array("i7_index_set_id"=>"1",  "index"=>"E01",  "sequence"=>"GCCAAGAC"),
                array("i7_index_set_id"=>"1",  "index"=>"F01",  "sequence"=>"GACTAGTA"),
                array("i7_index_set_id"=>"1",  "index"=>"G01",  "sequence"=>"ATTGGCTC"),
                array("i7_index_set_id"=>"1",  "index"=>"H01",  "sequence"=>"GATGAATC"),
                array("i7_index_set_id"=>"1",  "index"=>"A02",  "sequence"=>"AGCAGGAA"),
                array("i7_index_set_id"=>"1",  "index"=>"B02",  "sequence"=>"GAGCTGAA"),
                array("i7_index_set_id"=>"1",  "index"=>"C02",  "sequence"=>"AAACATCG"),
                array("i7_index_set_id"=>"1",  "index"=>"D02",  "sequence"=>"GAGTTAGC"),
                array("i7_index_set_id"=>"1",  "index"=>"E02",  "sequence"=>"CGAACTTA"),
                array("i7_index_set_id"=>"1",  "index"=>"F02",  "sequence"=>"GATAGACA"),
                array("i7_index_set_id"=>"1",  "index"=>"G02",  "sequence"=>"AAGGACAC"),
                array("i7_index_set_id"=>"1",  "index"=>"H02",  "sequence"=>"GACAGTGC"),
                array("i7_index_set_id"=>"1",  "index"=>"A03",  "sequence"=>"ATCATTCC"),
                array("i7_index_set_id"=>"1",  "index"=>"B03",  "sequence"=>"GCCACATA"),
                array("i7_index_set_id"=>"1",  "index"=>"C03",  "sequence"=>"ACCACTGT"),
                array("i7_index_set_id"=>"1",  "index"=>"D03",  "sequence"=>"CTGGCATA"),
                array("i7_index_set_id"=>"1",  "index"=>"E03",  "sequence"=>"ACCTCCAA"),
                array("i7_index_set_id"=>"1",  "index"=>"F03",  "sequence"=>"GCGAGTAA"),
                array("i7_index_set_id"=>"1",  "index"=>"G03",  "sequence"=>"ACTATGCA"),
                array("i7_index_set_id"=>"1",  "index"=>"H03",  "sequence"=>"CGGATTGC"),
                array("i7_index_set_id"=>"1",  "index"=>"A04",  "sequence"=>"AACTCACC"),
                array("i7_index_set_id"=>"1",  "index"=>"B04",  "sequence"=>"GCTAACGA"),
                array("i7_index_set_id"=>"1",  "index"=>"C04",  "sequence"=>"CAGATCTG"),
                array("i7_index_set_id"=>"1",  "index"=>"D04",  "sequence"=>"ATCCTGTA"),
                array("i7_index_set_id"=>"1",  "index"=>"E04",  "sequence"=>"CTGTAGCC"),
                array("i7_index_set_id"=>"1",  "index"=>"F04",  "sequence"=>"GCTCGGTA"),
                array("i7_index_set_id"=>"1",  "index"=>"G04",  "sequence"=>"ACACGACC"),
                array("i7_index_set_id"=>"1",  "index"=>"H04",  "sequence"=>"AGTCACTA"),
                array("i7_index_set_id"=>"1",  "index"=>"A05",  "sequence"=>"AACGCTTA"),
                array("i7_index_set_id"=>"1",  "index"=>"B05",  "sequence"=>"GGAGAACA"),
                array("i7_index_set_id"=>"1",  "index"=>"C05",  "sequence"=>"CATCAAGT"),
                array("i7_index_set_id"=>"1",  "index"=>"D05",  "sequence"=>"AAGGTACA"),
                array("i7_index_set_id"=>"1",  "index"=>"E05",  "sequence"=>"CGCTGATC"),
                array("i7_index_set_id"=>"1",  "index"=>"F05",  "sequence"=>"GGTGCGAA"),
                array("i7_index_set_id"=>"1",  "index"=>"G05",  "sequence"=>"CCTAATCC"),
                array("i7_index_set_id"=>"1",  "index"=>"H05",  "sequence"=>"CTGAGCCA"),
                array("i7_index_set_id"=>"1",  "index"=>"A06",  "sequence"=>"AGCCATGC"),
                array("i7_index_set_id"=>"1",  "index"=>"B06",  "sequence"=>"GTACGCAA"),
                array("i7_index_set_id"=>"1",  "index"=>"C06",  "sequence"=>"AGTACAAG"),
                array("i7_index_set_id"=>"1",  "index"=>"D06",  "sequence"=>"ACATTGGC"),
                array("i7_index_set_id"=>"1",  "index"=>"E06",  "sequence"=>"ATTGAGGA"),
                array("i7_index_set_id"=>"1",  "index"=>"F06",  "sequence"=>"GTCGTAGA"),
                array("i7_index_set_id"=>"1",  "index"=>"G06",  "sequence"=>"AGAGTCAA"),
                array("i7_index_set_id"=>"1",  "index"=>"H06",  "sequence"=>"CCGACAAC"),
                array("i7_index_set_id"=>"1",  "index"=>"A07",  "sequence"=>"ACGTATCA"),
                array("i7_index_set_id"=>"1",  "index"=>"B07",  "sequence"=>"GTCTGTCA"),
                array("i7_index_set_id"=>"1",  "index"=>"C07",  "sequence"=>"CTAAGGTC"),
                array("i7_index_set_id"=>"1",  "index"=>"D07",  "sequence"=>"CGACACAC"),
                array("i7_index_set_id"=>"1",  "index"=>"E07",  "sequence"=>"CCGTGAGA"),
                array("i7_index_set_id"=>"1",  "index"=>"F07",  "sequence"=>"GTGTTCTA"),
                array("i7_index_set_id"=>"1",  "index"=>"G07",  "sequence"=>"CAATGGAA"),
                array("i7_index_set_id"=>"1",  "index"=>"H07",  "sequence"=>"AGCACCTC"),
                array("i7_index_set_id"=>"1",  "index"=>"A08",  "sequence"=>"CAGCGTTA"),
                array("i7_index_set_id"=>"1",  "index"=>"B08",  "sequence"=>"TAGGATGA"),
                array("i7_index_set_id"=>"1",  "index"=>"C08",  "sequence"=>"AGTGGTCA"),
                array("i7_index_set_id"=>"1",  "index"=>"D08",  "sequence"=>"ACAGCAGA"),
                array("i7_index_set_id"=>"1",  "index"=>"E08",  "sequence"=>"CATACCAA"),
                array("i7_index_set_id"=>"1",  "index"=>"F08",  "sequence"=>"TATCAGCA"),
                array("i7_index_set_id"=>"1",  "index"=>"G08",  "sequence"=>"ATAGCGAC"),
                array("i7_index_set_id"=>"1",  "index"=>"H08",  "sequence"=>"ACGCTCGA"),
                array("i7_index_set_id"=>"1",  "index"=>"A09",  "sequence"=>"CTCAATGA"),
                array("i7_index_set_id"=>"1",  "index"=>"B09",  "sequence"=>"TCCGTCTA"),
                array("i7_index_set_id"=>"1",  "index"=>"C09",  "sequence"=>"AGGCTAAC"),
                array("i7_index_set_id"=>"1",  "index"=>"D09",  "sequence"=>"CCATCCTC"),
                array("i7_index_set_id"=>"1",  "index"=>"E09",  "sequence"=>"AGATGTAC"),
                array("i7_index_set_id"=>"1",  "index"=>"F09",  "sequence"=>"TCTTCACA"),
                array("i7_index_set_id"=>"1",  "index"=>"G09",  "sequence"=>"CCGAAGTA"),
                array("i7_index_set_id"=>"1",  "index"=>"H09",  "sequence"=>"CGCATACA"),
                array("i7_index_set_id"=>"1",  "index"=>"A10",  "sequence"=>"AATGTTGC"),
                array("i7_index_set_id"=>"1",  "index"=>"B10",  "sequence"=>"TGAAGAGA"),
                array("i7_index_set_id"=>"1",  "index"=>"C10",  "sequence"=>"AGATCGCA"),
                array("i7_index_set_id"=>"1",  "index"=>"D10",  "sequence"=>"AAGAGATC"),
                array("i7_index_set_id"=>"1",  "index"=>"E10",  "sequence"=>"CAACCACA"),
                array("i7_index_set_id"=>"1",  "index"=>"F10",  "sequence"=>"TGGAACAA"),
                array("i7_index_set_id"=>"1",  "index"=>"G10",  "sequence"=>"CCTCTATC"),
                array("i7_index_set_id"=>"1",  "index"=>"H10",  "sequence"=>"ACAGATTC"),
                array("i7_index_set_id"=>"1",  "index"=>"A11",  "sequence"=>"CCAGTTCA"),
                array("i7_index_set_id"=>"1",  "index"=>"B11",  "sequence"=>"TGGCTTCA"),
                array("i7_index_set_id"=>"1",  "index"=>"C11",  "sequence"=>"CGACTGGA"),
                array("i7_index_set_id"=>"1",  "index"=>"D11",  "sequence"=>"CAAGACTA"),
                array("i7_index_set_id"=>"1",  "index"=>"E11",  "sequence"=>"CCTCCTGA"),
                array("i7_index_set_id"=>"1",  "index"=>"F11",  "sequence"=>"TGGTGGTA"),
                array("i7_index_set_id"=>"1",  "index"=>"G11",  "sequence"=>"AACAACCA"),
                array("i7_index_set_id"=>"1",  "index"=>"H11",  "sequence"=>"AATCCGTC"),
                array("i7_index_set_id"=>"1",  "index"=>"A12",  "sequence"=>"CAAGGAGC"),
                array("i7_index_set_id"=>"1",  "index"=>"B12",  "sequence"=>"TTCACGCA"),
                array("i7_index_set_id"=>"1",  "index"=>"C12",  "sequence"=>"CACCTTAC"),
                array("i7_index_set_id"=>"1",  "index"=>"D12",  "sequence"=>"AAGACGGA"),
                array("i7_index_set_id"=>"1",  "index"=>"E12",  "sequence"=>"ACACAGAA"),
                array("i7_index_set_id"=>"1",  "index"=>"F12",  "sequence"=>"GAACAGGC"),
                array("i7_index_set_id"=>"1",  "index"=>"G12",  "sequence"=>"AACCGAGA"),
                array("i7_index_set_id"=>"1",  "index"=>"H12",  "sequence"=>"ACAAGCTA"),

                array("i7_index_set_id"=>"2",  "index"=>"1",  "sequence"=>"AACGTGAT"),
                array("i7_index_set_id"=>"2",  "index"=>"2",  "sequence"=>"AAACATCG"),
                array("i7_index_set_id"=>"2",  "index"=>"3",  "sequence"=>"ATGCCTAA"),
                array("i7_index_set_id"=>"2",  "index"=>"4",  "sequence"=>"AGTGGTCA"),
                array("i7_index_set_id"=>"2",  "index"=>"5",  "sequence"=>"ACCACTGT"),
                array("i7_index_set_id"=>"2",  "index"=>"6",  "sequence"=>"ACATTGGC"),
                array("i7_index_set_id"=>"2",  "index"=>"7",  "sequence"=>"CAGATCTG"),
                array("i7_index_set_id"=>"2",  "index"=>"8",  "sequence"=>"CATCAAGT"),
                array("i7_index_set_id"=>"2",  "index"=>"9",  "sequence"=>"CGCTGATC"),
                array("i7_index_set_id"=>"2",  "index"=>"10",  "sequence"=>"ACAAGCTA"),
                array("i7_index_set_id"=>"2",  "index"=>"11",  "sequence"=>"CTGTAGCC"),
                array("i7_index_set_id"=>"2",  "index"=>"12",  "sequence"=>"AGTACAAG"),
                array("i7_index_set_id"=>"2",  "index"=>"13",  "sequence"=>"AACAACCA"),
                array("i7_index_set_id"=>"2",  "index"=>"14",  "sequence"=>"AACCGAGA"),
                array("i7_index_set_id"=>"2",  "index"=>"15",  "sequence"=>"AACGCTTA"),
                array("i7_index_set_id"=>"2",  "index"=>"16",  "sequence"=>"AAGACGGA"),
                array("i7_index_set_id"=>"2",  "index"=>"17",  "sequence"=>"AAGGTACA"),
                array("i7_index_set_id"=>"2",  "index"=>"18",  "sequence"=>"ACACAGAA"),
                array("i7_index_set_id"=>"2",  "index"=>"19",  "sequence"=>"ACAGCAGA"),
                array("i7_index_set_id"=>"2",  "index"=>"20",  "sequence"=>"ACCTCCAA"),
                array("i7_index_set_id"=>"2",  "index"=>"21",  "sequence"=>"ACGCTCGA"),
                array("i7_index_set_id"=>"2",  "index"=>"22",  "sequence"=>"ACGTATCA"),
                array("i7_index_set_id"=>"2",  "index"=>"23",  "sequence"=>"ACTATGCA"),
                array("i7_index_set_id"=>"2",  "index"=>"24",  "sequence"=>"AGAGTCAA"),
                array("i7_index_set_id"=>"2",  "index"=>"25",  "sequence"=>"AGATCGCA"),
                array("i7_index_set_id"=>"2",  "index"=>"26",  "sequence"=>"AGCAGGAA"),
                array("i7_index_set_id"=>"2",  "index"=>"27",  "sequence"=>"AGTCACTA"),
                array("i7_index_set_id"=>"2",  "index"=>"28",  "sequence"=>"ATCCTGTA"),
                array("i7_index_set_id"=>"2",  "index"=>"29",  "sequence"=>"ATTGAGGA"),
                array("i7_index_set_id"=>"2",  "index"=>"30",  "sequence"=>"CAACCACA"),
                array("i7_index_set_id"=>"2",  "index"=>"31",  "sequence"=>"CAAGACTA"),
                array("i7_index_set_id"=>"2",  "index"=>"32",  "sequence"=>"CAATGGAA"),
                array("i7_index_set_id"=>"2",  "index"=>"33",  "sequence"=>"CACTTCGA"),
                array("i7_index_set_id"=>"2",  "index"=>"34",  "sequence"=>"CAGCGTTA"),
                array("i7_index_set_id"=>"2",  "index"=>"35",  "sequence"=>"CATACCAA"),
                array("i7_index_set_id"=>"2",  "index"=>"36",  "sequence"=>"CCAGTTCA"),
                array("i7_index_set_id"=>"2",  "index"=>"37",  "sequence"=>"CCGAAGTA"),
                array("i7_index_set_id"=>"2",  "index"=>"38",  "sequence"=>"CCGTGAGA"),
                array("i7_index_set_id"=>"2",  "index"=>"39",  "sequence"=>"CCTCCTGA"),
                array("i7_index_set_id"=>"2",  "index"=>"40",  "sequence"=>"CGAACTTA"),
                array("i7_index_set_id"=>"2",  "index"=>"41",  "sequence"=>"CGACTGGA"),
                array("i7_index_set_id"=>"2",  "index"=>"42",  "sequence"=>"CGCATACA"),
                array("i7_index_set_id"=>"2",  "index"=>"43",  "sequence"=>"CTCAATGA"),
                array("i7_index_set_id"=>"2",  "index"=>"44",  "sequence"=>"CTGAGCCA"),
                array("i7_index_set_id"=>"2",  "index"=>"45",  "sequence"=>"CTGGCATA"),
                array("i7_index_set_id"=>"2",  "index"=>"46",  "sequence"=>"GAATCTGA"),
                array("i7_index_set_id"=>"2",  "index"=>"47",  "sequence"=>"GACTAGTA"),
                array("i7_index_set_id"=>"2",  "index"=>"48",  "sequence"=>"GAGCTGAA"),
                array("i7_index_set_id"=>"2",  "index"=>"49",  "sequence"=>"GATAGACA"),
                array("i7_index_set_id"=>"2",  "index"=>"50",  "sequence"=>"GCCACATA"),
                array("i7_index_set_id"=>"2",  "index"=>"51",  "sequence"=>"GCGAGTAA"),
                array("i7_index_set_id"=>"2",  "index"=>"52",  "sequence"=>"GCTAACGA"),
                array("i7_index_set_id"=>"2",  "index"=>"53",  "sequence"=>"GCTCGGTA"),
                array("i7_index_set_id"=>"2",  "index"=>"54",  "sequence"=>"GGAGAACA"),
                array("i7_index_set_id"=>"2",  "index"=>"55",  "sequence"=>"GGTGCGAA"),
                array("i7_index_set_id"=>"2",  "index"=>"56",  "sequence"=>"GTACGCAA"),
                array("i7_index_set_id"=>"2",  "index"=>"57",  "sequence"=>"GTCGTAGA"),
                array("i7_index_set_id"=>"2",  "index"=>"58",  "sequence"=>"GTCTGTCA"),
                array("i7_index_set_id"=>"2",  "index"=>"59",  "sequence"=>"GTGTTCTA"),
                array("i7_index_set_id"=>"2",  "index"=>"60",  "sequence"=>"TAGGATGA"),
                array("i7_index_set_id"=>"2",  "index"=>"61",  "sequence"=>"TATCAGCA"),
                array("i7_index_set_id"=>"2",  "index"=>"62",  "sequence"=>"TCCGTCTA"),
                array("i7_index_set_id"=>"2",  "index"=>"63",  "sequence"=>"TCTTCACA"),
                array("i7_index_set_id"=>"2",  "index"=>"64",  "sequence"=>"TGAAGAGA"),
                array("i7_index_set_id"=>"2",  "index"=>"65",  "sequence"=>"TGGAACAA"),
                array("i7_index_set_id"=>"2",  "index"=>"66",  "sequence"=>"TGGCTTCA"),
                array("i7_index_set_id"=>"2",  "index"=>"67",  "sequence"=>"TGGTGGTA"),
                array("i7_index_set_id"=>"2",  "index"=>"68",  "sequence"=>"TTCACGCA"),
                array("i7_index_set_id"=>"2",  "index"=>"69",  "sequence"=>"AACTCACC"),
                array("i7_index_set_id"=>"2",  "index"=>"70",  "sequence"=>"AAGAGATC"),
                array("i7_index_set_id"=>"2",  "index"=>"71",  "sequence"=>"AAGGACAC"),
                array("i7_index_set_id"=>"2",  "index"=>"72",  "sequence"=>"AATCCGTC"),
                array("i7_index_set_id"=>"2",  "index"=>"73",  "sequence"=>"AATGTTGC"),
                array("i7_index_set_id"=>"2",  "index"=>"74",  "sequence"=>"ACACGACC"),
                array("i7_index_set_id"=>"2",  "index"=>"75",  "sequence"=>"ACAGATTC"),
                array("i7_index_set_id"=>"2",  "index"=>"76",  "sequence"=>"AGATGTAC"),
                array("i7_index_set_id"=>"2",  "index"=>"77",  "sequence"=>"AGCACCTC"),
                array("i7_index_set_id"=>"2",  "index"=>"78",  "sequence"=>"AGCCATGC"),
                array("i7_index_set_id"=>"2",  "index"=>"79",  "sequence"=>"AGGCTAAC"),
                array("i7_index_set_id"=>"2",  "index"=>"80",  "sequence"=>"ATAGCGAC"),
                array("i7_index_set_id"=>"2",  "index"=>"81",  "sequence"=>"ATCATTCC"),
                array("i7_index_set_id"=>"2",  "index"=>"82",  "sequence"=>"ATTGGCTC"),
                array("i7_index_set_id"=>"2",  "index"=>"83",  "sequence"=>"CAAGGAGC"),
                array("i7_index_set_id"=>"2",  "index"=>"84",  "sequence"=>"CACCTTAC"),
                array("i7_index_set_id"=>"2",  "index"=>"85",  "sequence"=>"CCATCCTC"),
                array("i7_index_set_id"=>"2",  "index"=>"86",  "sequence"=>"CCGACAAC"),
                array("i7_index_set_id"=>"2",  "index"=>"87",  "sequence"=>"CCTAATCC"),
                array("i7_index_set_id"=>"2",  "index"=>"88",  "sequence"=>"CCTCTATC"),
                array("i7_index_set_id"=>"2",  "index"=>"89",  "sequence"=>"CGACACAC"),
                array("i7_index_set_id"=>"2",  "index"=>"90",  "sequence"=>"CGGATTGC"),
                array("i7_index_set_id"=>"2",  "index"=>"91",  "sequence"=>"CTAAGGTC"),
                array("i7_index_set_id"=>"2",  "index"=>"92",  "sequence"=>"GAACAGGC"),
                array("i7_index_set_id"=>"2",  "index"=>"93",  "sequence"=>"GACAGTGC"),
                array("i7_index_set_id"=>"2",  "index"=>"94",  "sequence"=>"GAGTTAGC"),
                array("i7_index_set_id"=>"2",  "index"=>"95",  "sequence"=>"GATGAATC"),
                array("i7_index_set_id"=>"2",  "index"=>"96",  "sequence"=>"GCCAAGAC"),

                array("i7_index_set_id"=>"3",  "index"=>"N701",  "sequence"=>"TAAGGCGA"),
                array("i7_index_set_id"=>"3",  "index"=>"N702",  "sequence"=>"CGTACTAG"),
                array("i7_index_set_id"=>"3",  "index"=>"N703",  "sequence"=>"AGGCAGAA"),
                array("i7_index_set_id"=>"3",  "index"=>"N704",  "sequence"=>"TCCTGAGC"),
                array("i7_index_set_id"=>"3",  "index"=>"N705",  "sequence"=>"GGACTCCT"),
                array("i7_index_set_id"=>"3",  "index"=>"N706",  "sequence"=>"TAGGCATG"),
                array("i7_index_set_id"=>"3",  "index"=>"N707",  "sequence"=>"CTCTCTAC"),
                array("i7_index_set_id"=>"3",  "index"=>"N708",  "sequence"=>"CAGAGAGG"),
                array("i7_index_set_id"=>"3",  "index"=>"N709",  "sequence"=>"GCTACGCT"),
                array("i7_index_set_id"=>"3",  "index"=>"N710",  "sequence"=>"CGAGGCTG"),
                array("i7_index_set_id"=>"3",  "index"=>"N711",  "sequence"=>"AAGAGGCA"),
                array("i7_index_set_id"=>"3",  "index"=>"N712",  "sequence"=>"GTAGAGGA"),

                array("i7_index_set_id"=>"4",  "index"=>"N701",  "sequence"=>"TCGCCTTA"),
                array("i7_index_set_id"=>"4",  "index"=>"N702",  "sequence"=>"CTAGTACG"),
                array("i7_index_set_id"=>"4",  "index"=>"N703",  "sequence"=>"TTCTGCCT"),
                array("i7_index_set_id"=>"4",  "index"=>"N704",  "sequence"=>"GCTCAGGA"),
                array("i7_index_set_id"=>"4",  "index"=>"N705",  "sequence"=>"AGGAGTCC"),
                array("i7_index_set_id"=>"4",  "index"=>"N706",  "sequence"=>"CATGCCTA"),
                array("i7_index_set_id"=>"4",  "index"=>"N707",  "sequence"=>"GTAGAGAG"),
                array("i7_index_set_id"=>"4",  "index"=>"N710",  "sequence"=>"CAGCCTCG"),
                array("i7_index_set_id"=>"4",  "index"=>"N711",  "sequence"=>"TGCCTCTT"),
                array("i7_index_set_id"=>"4",  "index"=>"N712",  "sequence"=>"TCCTCTAC"),
                array("i7_index_set_id"=>"4",  "index"=>"N714",  "sequence"=>"TCATGAGC"),
                array("i7_index_set_id"=>"4",  "index"=>"N715",  "sequence"=>"CCTGAGAT"),
                array("i7_index_set_id"=>"4",  "index"=>"N716",  "sequence"=>"TAGCGAGT"),
                array("i7_index_set_id"=>"4",  "index"=>"N718",  "sequence"=>"GTAGCTCC"),
                array("i7_index_set_id"=>"4",  "index"=>"N719",  "sequence"=>"TACTACGC"),
                array("i7_index_set_id"=>"4",  "index"=>"N720",  "sequence"=>"AGGCTCCG"),
                array("i7_index_set_id"=>"4",  "index"=>"N721",  "sequence"=>"GCAGCGTA"),
                array("i7_index_set_id"=>"4",  "index"=>"N722",  "sequence"=>"CTGCGCAT"),
                array("i7_index_set_id"=>"4",  "index"=>"N723",  "sequence"=>"GAGCGCTA"),
                array("i7_index_set_id"=>"4",  "index"=>"N724",  "sequence"=>"CGCTCAGT"),

                array("i7_index_set_id"=>"5",  "index"=>"D701",  "sequence"=>"ATTACTCG"),
                array("i7_index_set_id"=>"5",  "index"=>"D702",  "sequence"=>"TCCGGAGA"),
                array("i7_index_set_id"=>"5",  "index"=>"D703",  "sequence"=>"CGCTCATT"),
                array("i7_index_set_id"=>"5",  "index"=>"D704",  "sequence"=>"GAGATTCC"),
                array("i7_index_set_id"=>"5",  "index"=>"D705",  "sequence"=>"ATTCAGAA"),
                array("i7_index_set_id"=>"5",  "index"=>"D706",  "sequence"=>"GAATTCGT"),
                array("i7_index_set_id"=>"5",  "index"=>"D707",  "sequence"=>"CTGAAGCT"),
                array("i7_index_set_id"=>"5",  "index"=>"D708",  "sequence"=>"TAATGCGC"),
                array("i7_index_set_id"=>"5",  "index"=>"D709",  "sequence"=>"CGGCTATG"),
                array("i7_index_set_id"=>"5",  "index"=>"D710",  "sequence"=>"TCCGCGAA"),
                array("i7_index_set_id"=>"5",  "index"=>"D711",  "sequence"=>"TCTCGCGC"),
                array("i7_index_set_id"=>"5",  "index"=>"D712",  "sequence"=>"AGCGATAG"),

                array("i7_index_set_id"=>"6",  "index"=>"AR002",  "sequence"=>"CGATGT"),
                array("i7_index_set_id"=>"6",  "index"=>"AR004",  "sequence"=>"TGACCA"),
                array("i7_index_set_id"=>"6",  "index"=>"AR005",  "sequence"=>"ACAGTG"),
                array("i7_index_set_id"=>"6",  "index"=>"AR006",  "sequence"=>"GCCAAT"),
                array("i7_index_set_id"=>"6",  "index"=>"AR007",  "sequence"=>"CAGATC"),
                array("i7_index_set_id"=>"6",  "index"=>"AR012",  "sequence"=>"CTTGTA"),
                array("i7_index_set_id"=>"6",  "index"=>"AR001",  "sequence"=>"ATCACG"),
                array("i7_index_set_id"=>"6",  "index"=>"AR003",  "sequence"=>"TTAGGC"),
                array("i7_index_set_id"=>"6",  "index"=>"AR008",  "sequence"=>"ACTTGA"),
                array("i7_index_set_id"=>"6",  "index"=>"AR009",  "sequence"=>"GATCAG"),
                array("i7_index_set_id"=>"6",  "index"=>"AR010",  "sequence"=>"TAGCTT"),
                array("i7_index_set_id"=>"6",  "index"=>"AR011",  "sequence"=>"GGCTAC"),
                array("i7_index_set_id"=>"6",  "index"=>"AR013",  "sequence"=>"AGTCAA"),
                array("i7_index_set_id"=>"6",  "index"=>"AR014",  "sequence"=>"AGTTCC"),
                array("i7_index_set_id"=>"6",  "index"=>"AR015",  "sequence"=>"ATGTCA"),
                array("i7_index_set_id"=>"6",  "index"=>"AR016",  "sequence"=>"CCGTCC"),
                array("i7_index_set_id"=>"6",  "index"=>"AR018",  "sequence"=>"GTCCGC"),
                array("i7_index_set_id"=>"6",  "index"=>"AR019",  "sequence"=>"GTGAAA"),
                array("i7_index_set_id"=>"6",  "index"=>"AR020",  "sequence"=>"GTGGCC"),
                array("i7_index_set_id"=>"6",  "index"=>"AR021",  "sequence"=>"GTTTCG"),
                array("i7_index_set_id"=>"6",  "index"=>"AR022",  "sequence"=>"CGTACG"),
                array("i7_index_set_id"=>"6",  "index"=>"AR023",  "sequence"=>"GAGTGG"),
                array("i7_index_set_id"=>"6",  "index"=>"AR025",  "sequence"=>"ACTGAT"),
                array("i7_index_set_id"=>"6",  "index"=>"AR027",  "sequence"=>"ATTCCT"),

                array("i7_index_set_id"=>"7",  "index"=>"RPI1",  "sequence"=>"ATCACG"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI2",  "sequence"=>"CGATGT"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI3",  "sequence"=>"TTAGGC"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI4",  "sequence"=>"TGACCA"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI5",  "sequence"=>"ACAGTG"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI6",  "sequence"=>"GCCAAT"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI13",  "sequence"=>"AGTCAA"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI14",  "sequence"=>"AGTTCC"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI15",  "sequence"=>"ATGTCA"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI16",  "sequence"=>"CCGTCC"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI17",  "sequence"=>"GTAGAG"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI18",  "sequence"=>"GTCCGC"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI25",  "sequence"=>"ACTGAT"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI26",  "sequence"=>"ATGAGC"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI27",  "sequence"=>"ATTCCT"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI28",  "sequence"=>"CAAAAG"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI29",  "sequence"=>"CAACTA"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI30",  "sequence"=>"CACCGG"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI37",  "sequence"=>"CGGAAT"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI38",  "sequence"=>"CTAGCT"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI39",  "sequence"=>"CTATAC"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI40",  "sequence"=>"CTCAGA"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI41",  "sequence"=>"GACGAC"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI42",  "sequence"=>"TAATCG"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI7",  "sequence"=>"CAGATC"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI8",  "sequence"=>"ACTTGA"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI9",  "sequence"=>"GATCAG"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI10",  "sequence"=>"TAGCTT"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI11",  "sequence"=>"GGCTAC"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI12",  "sequence"=>"CTTGTA"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI19",  "sequence"=>"GTGAAA"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI20",  "sequence"=>"GTGGCC"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI21",  "sequence"=>"GTTTCG"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI22",  "sequence"=>"CGTACG"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI23",  "sequence"=>"GAGTGG"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI24",  "sequence"=>"GGTAGC"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI31",  "sequence"=>"CACGAT"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI32",  "sequence"=>"CACTCA"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI33",  "sequence"=>"CAGGCG"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI34",  "sequence"=>"CATGGC"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI35",  "sequence"=>"CATTTT"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI36",  "sequence"=>"CCAACA"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI43",  "sequence"=>"TACAGC"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI44",  "sequence"=>"TATAAT"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI45",  "sequence"=>"TCATTC"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI46",  "sequence"=>"TCCCGA"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI47",  "sequence"=>"TCGAAG"),
                array("i7_index_set_id"=>"7",  "index"=>"RPI48",  "sequence"=>"TCGGCA"),

                array("i7_index_set_id"=>"8",  "index"=>"ILIND01",  "sequence"=>"ATCACG"),
                array("i7_index_set_id"=>"8",  "index"=>"ILIND02",  "sequence"=>"CGATGT"),
                array("i7_index_set_id"=>"8",  "index"=>"ILIND03",  "sequence"=>"TTAGGC"),
                array("i7_index_set_id"=>"8",  "index"=>"ILIND04",  "sequence"=>"TGACCA"),
                array("i7_index_set_id"=>"8",  "index"=>"ILIND05",  "sequence"=>"ACAGTG"),
                array("i7_index_set_id"=>"8",  "index"=>"ILIND06",  "sequence"=>"GCCAAT"),
                array("i7_index_set_id"=>"8",  "index"=>"ILIND07",  "sequence"=>"CAGATC"),
                array("i7_index_set_id"=>"8",  "index"=>"ILIND08",  "sequence"=>"ACTTGA"),
                array("i7_index_set_id"=>"8",  "index"=>"ILIND09",  "sequence"=>"GATCAG"),
                array("i7_index_set_id"=>"8",  "index"=>"ILIND10",  "sequence"=>"TAGCTT"),
                array("i7_index_set_id"=>"8",  "index"=>"ILIND11",  "sequence"=>"GGCTAC"),
                array("i7_index_set_id"=>"8",  "index"=>"ILIND12",  "sequence"=>"CTTGTA"),

                array("i7_index_set_id"=>"9",  "index"=>"mpxPEII_bc001",  "sequence"=>"TACGAAGT"),
                array("i7_index_set_id"=>"9",  "index"=>"mpxPEII_bc002",  "sequence"=>"GACGAGAT"),
                array("i7_index_set_id"=>"9",  "index"=>"mpxPEII_bc003",  "sequence"=>"TAGTGGCA"),
                array("i7_index_set_id"=>"9",  "index"=>"mpxPEII_bc004",  "sequence"=>"CATTAACG"),
                array("i7_index_set_id"=>"9",  "index"=>"mpxPEII_bc005",  "sequence"=>"TCGTTGAA"),
                array("i7_index_set_id"=>"9",  "index"=>"mpxPEII_bc006",  "sequence"=>"TAGTACGC"),
                array("i7_index_set_id"=>"9",  "index"=>"mpxPEII_bc007",  "sequence"=>"TTCACCGT"),
                array("i7_index_set_id"=>"9",  "index"=>"mpxPEII_bc008",  "sequence"=>"AGGACAGT"),
                array("i7_index_set_id"=>"9",  "index"=>"mpxPEII_bc009",  "sequence"=>"AATCGTGG"),
                array("i7_index_set_id"=>"9",  "index"=>"mpxPEII_bc010",  "sequence"=>"GTATCAGT"),
                array("i7_index_set_id"=>"9",  "index"=>"mpxPEII_bc011",  "sequence"=>"AGCAGATG"),
                array("i7_index_set_id"=>"9",  "index"=>"mpxPEII_bc012",  "sequence"=>"TCCTAACG"),
                array("i7_index_set_id"=>"9",  "index"=>"mpxPEII_bc013",  "sequence"=>"TGTCTAGT"),
                array("i7_index_set_id"=>"9",  "index"=>"mpxPEII_bc014",  "sequence"=>"TGAATGCC"),
                array("i7_index_set_id"=>"9",  "index"=>"mpxPEII_bc015",  "sequence"=>"GTGCAATG"),
                array("i7_index_set_id"=>"9",  "index"=>"mpxPEII_bc016",  "sequence"=>"AGTGGCAT"),
                array("i7_index_set_id"=>"9",  "index"=>"mpxPEII_bc017",  "sequence"=>"AGTCTACC"),
                array("i7_index_set_id"=>"9",  "index"=>"mpxPEII_bc018",  "sequence"=>"ATCGGTAG"),
                array("i7_index_set_id"=>"9",  "index"=>"mpxPEII_bc019",  "sequence"=>"CGTATGAT"),
                array("i7_index_set_id"=>"9",  "index"=>"mpxPEII_bc020",  "sequence"=>"CTGTCGTA"),
                array("i7_index_set_id"=>"9",  "index"=>"mpxPEII_bc021",  "sequence"=>"TCAACTGG"),
                array("i7_index_set_id"=>"9",  "index"=>"mpxPEII_bc022",  "sequence"=>"ATCGATCT"),
                array("i7_index_set_id"=>"9",  "index"=>"mpxPEII_bc023",  "sequence"=>"GCAACTAT"),
                array("i7_index_set_id"=>"9",  "index"=>"mpxPEII_bc024",  "sequence"=>"GATGACTT"),

                array("i7_index_set_id"=>"10",  "index"=>"IP01",  "sequence"=>"CTGTGT"),
                array("i7_index_set_id"=>"10",  "index"=>"IP02",  "sequence"=>"AGAGCT"),
                array("i7_index_set_id"=>"10",  "index"=>"IP03",  "sequence"=>"GCTGTG"),
                array("i7_index_set_id"=>"10",  "index"=>"IP04",  "sequence"=>"GCCATG"),
                array("i7_index_set_id"=>"10",  "index"=>"IP05",  "sequence"=>"TGTCAC"),
                array("i7_index_set_id"=>"10",  "index"=>"IP06",  "sequence"=>"CAGCAC"),
                array("i7_index_set_id"=>"10",  "index"=>"IP07",  "sequence"=>"ATATGA"),
                array("i7_index_set_id"=>"10",  "index"=>"IP08",  "sequence"=>"TACACA"),
                array("i7_index_set_id"=>"10",  "index"=>"IP09",  "sequence"=>"TGCTGT"),
                array("i7_index_set_id"=>"10",  "index"=>"IP10",  "sequence"=>"AGATCT"),
                array("i7_index_set_id"=>"10",  "index"=>"IP11",  "sequence"=>"TAGCTG"),
                array("i7_index_set_id"=>"10",  "index"=>"IP12",  "sequence"=>"GATCAG"),
                array("i7_index_set_id"=>"10",  "index"=>"IP13",  "sequence"=>"GCGAGC"),
                array("i7_index_set_id"=>"10",  "index"=>"IP14",  "sequence"=>"CTAGAC"),
                array("i7_index_set_id"=>"10",  "index"=>"IP15",  "sequence"=>"ACTGTA"),
                array("i7_index_set_id"=>"10",  "index"=>"IP16",  "sequence"=>"CTCACA"),
                array("i7_index_set_id"=>"10",  "index"=>"IP17",  "sequence"=>"GTCAGT"),
                array("i7_index_set_id"=>"10",  "index"=>"IP18",  "sequence"=>"TGACAT"),
                array("i7_index_set_id"=>"10",  "index"=>"IP19",  "sequence"=>"ACTGCG"),
                array("i7_index_set_id"=>"10",  "index"=>"IP20",  "sequence"=>"TGATAG"),
                array("i7_index_set_id"=>"10",  "index"=>"IP21",  "sequence"=>"CACGTC"),
                array("i7_index_set_id"=>"10",  "index"=>"IP22",  "sequence"=>"CATCGC"),
                array("i7_index_set_id"=>"10",  "index"=>"IP23",  "sequence"=>"GTGATA"),
                array("i7_index_set_id"=>"10",  "index"=>"IP24",  "sequence"=>"ACGTCA"),


                array("i7_index_set_id"=>"11",  "index"=>"TS-INV-HE-01",  "sequence"=>"ATCACG"),
                array("i7_index_set_id"=>"11",  "index"=>"TS-INV-HE-02",  "sequence"=>"CGATGT"),
                array("i7_index_set_id"=>"11",  "index"=>"TS-INV-HE-03",  "sequence"=>"TTAGGC"),
                array("i7_index_set_id"=>"11",  "index"=>"TS-INV-HE-04",  "sequence"=>"TGACCA"),
                array("i7_index_set_id"=>"11",  "index"=>"TS-INV-HE-05",  "sequence"=>"ACAGTG"),
                array("i7_index_set_id"=>"11",  "index"=>"TS-INV-HE-06",  "sequence"=>"GCCAAT"),
                array("i7_index_set_id"=>"11",  "index"=>"TS-INV-HE-07",  "sequence"=>"CAGATC"),
                array("i7_index_set_id"=>"11",  "index"=>"TS-INV-HE-08",  "sequence"=>"ACTTGA"),
                array("i7_index_set_id"=>"11",  "index"=>"TS-INV-HE-09",  "sequence"=>"GATCAG"),
                array("i7_index_set_id"=>"11",  "index"=>"TS-INV-HE-10",  "sequence"=>"TAGCTT"),
                array("i7_index_set_id"=>"11",  "index"=>"TS-INV-HE-11",  "sequence"=>"GGCTAC"),
                array("i7_index_set_id"=>"11",  "index"=>"TS-INV-HE-12",  "sequence"=>"CTTGTA"),
                array("i7_index_set_id"=>"11",  "index"=>"TS-INV-HE-13",  "sequence"=>"AGTCAA"),
                array("i7_index_set_id"=>"11",  "index"=>"TS-INV-HE-14",  "sequence"=>"AGTTCC"),
                array("i7_index_set_id"=>"11",  "index"=>"TS-INV-HE-15",  "sequence"=>"ATGTCA"),
                array("i7_index_set_id"=>"11",  "index"=>"TS-INV-HE-16",  "sequence"=>"CCGTCC"),
                array("i7_index_set_id"=>"11",  "index"=>"TS-INV-HE-18",  "sequence"=>"GTCCGC"),
                array("i7_index_set_id"=>"11",  "index"=>"TS-INV-HE-19",  "sequence"=>"GTGAAA"),
                array("i7_index_set_id"=>"11",  "index"=>"TS-INV-HE-20",  "sequence"=>"GTGGCC"),
                array("i7_index_set_id"=>"11",  "index"=>"TS-INV-HE-21",  "sequence"=>"GTTTCG"),
                array("i7_index_set_id"=>"11",  "index"=>"TS-INV-HE-22",  "sequence"=>"CGTACG"),
                array("i7_index_set_id"=>"11",  "index"=>"TS-INV-HE-23",  "sequence"=>"GAGTGG"),
                array("i7_index_set_id"=>"11",  "index"=>"TS-INV-HE-25",  "sequence"=>"ACTGAT"),
                array("i7_index_set_id"=>"11",  "index"=>"TS-INV-HE-27",  "sequence"=>"ATTCCT")


            ));

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop('i7_index');
    }
}
